#!/bin/bash
# Run vcast generated in the specified BUILDDIR.
#
# This provides the same feature as "ninja run", except that it is possible to
# pass arguments to vcast.
#
# Syntax: ./run BUILDDIR <vcast options ...>
if [[ $# = 0 ]]
then
    echo "Syntax: $0 BUILDDIR <vcast options>" >&2
    exit 1
fi

BUILDDIR="$1"
shift

if [[ ! -d "$BUILDDIR" ]]
then
    echo "The build dir \"$BUILDDIR\" does not exist." >&2
    exit 1
fi

vcast_SERVER_PATH="$BUILDDIR/server/vcast-server" "$BUILDDIR/app/vcast" "$@"
